14-microbiome-diversity.Rmd
18-multitable.Rmd
book.bib

I started to list the available options for representing multiassay/multitable data. It might be good work out a set of recommendations on how to represent differen scenarios. We have at least 
1. transformations (counts, relabundance, clr etc) -> assays()
2. alternative experiments (e.g 16S vs metagenomics for taxonomic abundances) -> assays() or altExp()
3. multiple experiments (e.g. taxonomic abundances vs. metaT or metabolomics) -> assays() or altExp() or MAE.

Multiassay

---

01-introduction.Rmd

Addressing [mia #87](https://github.com/microbiome/mia/issues/87).

Added example on CSV data import

---

15-microbiome-community.Rmd

Transferred from course material the section about community typing, to the dedicated one at OMA; file: 15-microbiome-community.Rmd

Adding content to the community typing section.

---

01-introduction.Rmd

Hi, 
Section 1.8 for additional reading has been added. Related issue #35

Additional reading; issue #35

---

14-microbiome-diversity.Rmd

A draft version of the content described at discussion/issue #33

Adding draft material; issue 33

---

15-microbiome-community.Rmd

Hi,
In the following an example of composition barplot has been added to "Community composition" sub-section.
This is related to microbiome/miaViz#20 Composition barplot.

Adding composition barplot.

---

12-quality-control.Rmd

Hi,
I added a histogram example that visualizes library size distribution.
Issue: https://github.com/microbiome/OMA/issues/15
-Tuomas

Added histogram example of library size visualization

---

14a_alpha_diversity.Rmd

Hi,
here are an example of boxplot that visualizes Shannon index, and an example of pairwise Wilcoxon test.
-Tuomas

Alpha diversity boxplot example

---

99_interactive_3d_plots.Rmd

Creating Temporarily a separate appendix for extras.

New appendix

---

14_alpha_diversity.Rmd

Hi,
here is an example of rarity index.
Issue: https://github.com/microbiome/OMA/issues/27
-Tuomas

Added rarity index example

---

17_differential_abundance.Rmd

Hi,
Here is a draft concerning the discussion at #65 .

Adding draft.

---

13_microbiome_exploration.Rmd
book.bib

The PR is for fixing the references at "book.bib" and "13_microbiome_exploration.Rmd" earlier merged.

Fixing references

---

16_microbiome_community.Rmd
book.bib

This is a draft example of using the package  [bluster](https://www.bioconductor.org/packages/devel/bioc/vignettes/bluster/inst/doc/clusterRows.html), graph based clustering for community discovery.
Related issue #61 .

Adding draft example.

---

16_microbiome_community.Rmd

Hi,
here are some examples of heatmaps.
-Tuomas

Added some exampled of heatmaps

---

01_intro.Rmd
04_datainfra.Rmd
11_taxonomic_information.Rmd
12_quality_control.Rmd
13_microbiome_exploration.Rmd
14_alpha_diversity.Rmd
15_beta_diversity.Rmd
16_microbiome_community.Rmd
17_differential_abundance.Rmd
19_multitable.Rmd
README.md

Hello! I reviewed the text as well as the comments in all the chapters of the book. The code was left unchanged.

Text Review

---

04_datainfra.Rmd

Add section on subsetting as 2.6 in "Data Infrastructure". Change name of the parent section  to "Data manipulation"

Add section on subsetting

---

.github/workflows/build-book-release.yml
23_multi-assay_analyses.Rmd
_bookdown.yml

Hi,
there was already a file that included cross-correlation example. I modified it and changed the data. Also, it was not included in OMA, but now there is a chapter dedicated to multi-assay analyses.
I'm not sure if that text about importing should be added. 
Issue: https://github.com/microbiome/OMA/issues/104
-Tuomas

Cross-correlation example to OMA

---

10_manipulation.Rmd

Hi,
this includes example of removing empty columns and rows. 
Issue: https://github.com/microbiome/mia/issues/173
-Tuomas

Added example of removing empty columns/rows

---

23_multi-assay_analyses.Rmd
book.bib

Hi,
The MOFA workflow examples is added, and the reference to the article.
Issue: #136

MOFA example

---

21_microbiome_community.Rmd

It seems that `agglomerateByRank` + `runMDS` in lines 446 - 456 were causing an overload, so I splitted chunk `dmm` into 2. Let's see if the PR check action succeeds...

Fix rendering issue

---

11_taxonomic_information.Rmd
19_visualization_techniques.Rmd
20_beta_diversity.Rmd
21_microbiome_community.Rmd
22_communitytyping.Rmd
23_multi-assay_analyses.Rmd
24_biclustering.Rmd
97_interactive_3d_plots.Rmd
98_exercises.Rmd
add-comm-typing.Rmd

https://github.com/microbiome/OMA/issues/171

PERMANOVA: by = margin, tasks, CLR

---

10_manipulation.Rmd
11_taxonomic_information.Rmd
12_quality_control.Rmd
14_alpha_diversity.Rmd
19_visualization_techniques.Rmd
20_beta_diversity.Rmd
21_microbiome_community.Rmd
23_multi-assay_analyses.Rmd
24_biclustering.Rmd
97_interactive_3d_plots.Rmd
add-comm-typing.Rmd

https://github.com/microbiome/OMA/issues/178

Replace abund_values with assay_name

---

19_visualization_techniques.Rmd
23_multi-assay_analyses.Rmd

Hi! I fixed the last couple of cross-references that weren't working.

Fix broken cross-references

---

97_extra_materials.Rmd

Hi!
I noticed that in [PERMANOVA comparison](https://microbiome.github.io/OMA/extras.html#permanova-comparison) section there are some duplicate lines, so I deleted them.
Just in case if you could double check.
Cheers!

Delete duplicate lines

---

06_packages.Rmd
20_beta_diversity.Rmd
97_extra_materials.Rmd

Hi!
Here I mainly fixed the link to the differential abundance chapter. Some additional improvements include replacing old cross-references and citations with bibtex format and adding some explanatory comments in my code.

Fix link to Differential Abundance chapter + some small improvements

---

30_differential_abundance.Rmd

I promised a while ago I will go over the DAA section in order to reference to new developments for ANCOMBC. ANCOMBC has become quite complex by now with lots of functionality. The simple example that we cover in the OMA book does not need this complexity. So, I kept the simple example but make the reader aware of possibilities/new developments and reference to the elaborate tutorials by the developer. I think that is the best solution for now. 
Regarding the other changes:
I noticed the code was broken due to package updates. Several packages handled the input differently compared to months ago. I assume that won't be the last time this happens. For now the code should be fixed but I left eval = FALSE as I am not sure when you want to make it evaluate on the server again.

fixed broken code + reference to new feature of ancombc2 function

---

10_manipulation.Rmd

I corrected typos, and made some enhancements for language clarity and text style. I also tried to make the text more consistent in using non-capitalized taxonomic rank names (i.e., phyla vs Phyla), and quotes ("").

Correct typos and improve style

---

10_manipulation.Rmd

Add example on adding or modifying colData

More manipulation

---

.github/workflows/build-book-release.yml
01_intro.Rmd

change in build-book-release.yml

Elina297 patch 1

---

24_clustering.Rmd

Added a bluster introduction to the clustering file where various examples with bluster are given.

Clustering with bluster

---

04_containers.Rmd
30_differential_abundance.Rmd
40_machine_learning.Rmd
80_training.Rmd
95_resources.Rmd

Hi! I moved the reproducible reporting section from course webpage to OMA. Something was already in OMA, so I just modified it. I also added outreach section in resources chapter with quarto presentations.

Update reproducible reporting and outreach

---

12_quality_control.Rmd
14_alpha_diversity.Rmd
20_beta_diversity.Rmd
21_microbiome_community.Rmd
22_communitytyping.Rmd
24_clustering.Rmd
30_differential_abundance.Rmd
80_training.Rmd
95_resources.Rmd
97_extra_materials.Rmd
98_exercises.Rmd

Hi! I reorganised the beta diversity chapter so that it has 2 main sections: unsupervized and supervized ordination. The first includes the previous sections on PCoA, other ordination methods and explained variance. The second includes the introduction to dbRDA. Then there is a third section on case studies, where testing differences between groups, plotting top taxa and other practical workflows are explained.
The main goal is to make this chapter well-structured and more approachable for newcomers.
The code should still be simplified, especially the dbRDA part, and standard combinations of assay transformation + ordination method should be discussed and used more consistently, but I'd plan it as a separate pull request.
I also capitalised all the titles of the book chapters because I …

Reorganise Chapter 8: Community similarity

---

.github/ISSUE_TEMPLATE/bug-report-🐞.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/pull-request.md
.github/ISSUE_TEMPLATE/user-support.md

A clear template supporting new issues

A clear template supporting new issues

---

.github/ISSUE_TEMPLATE/bug-report-🐞.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/pull-request.md
.github/ISSUE_TEMPLATE/user-support.md
_output.yml

Compare to OSCA & OSTA books #272
Added view, edit and history buttons after comparing to OSCA and OSTA

Adding some buttons to the navbar

---

.github/workflows/build-book-release.yml
11_taxonomic_information.Rmd
24_clustering.Rmd
DESCRIPTION

Reverts microbiome/OMA#295 because master had a check fail

Revert "Taxa clustering update"

---

04_containers.Rmd
98_exercises.Rmd
book.bib

Hi! I tried to make the biom import instruction clearer and put example datasets in microbiome/data repository

Streamline biom import section

---

04_containers.Rmd
19_visualization_techniques.Rmd
20_beta_diversity.Rmd
30_differential_abundance.Rmd
98_exercises.Rmd
book.bib

Hi! This PR is meant to streamline the DAA chapter and make the code easy to execute and read for future tutorials.

Simplify DAA chapter

---

20_beta_diversity.Rmd
23_multi-assay_analyses.Rmd
30_differential_abundance.Rmd
40_machine_learning.Rmd
95_resources.Rmd

Hi! Here I simplified the RDA section and clarified the DAA chapter. In particular:
- permanova testing is internally executed by runPCA, so no need to do it manually
- clarified complicated output of DAA with confounding variables
- added link to benchmarking repository

Improve RDA and DAA chapters

---

30_differential_abundance.Rmd
OMA.Rmd
R/30_differential_abundance.R

deprecate exprs_values and assay_name arguments

---

60_network_learning.Rmd
90_acknowledgments.Rmd

- Reorder network learning chapter to be less nested
- Move network plots to analysis section
- Add comment on closeness centrality
- Add contributors

Update network chapter and contributors

---

inst/pages/98_exercises.qmd

Hi! Before switching to BiocBook we were considering to add foldable solutions to the exercises. Here I added solution chunks to a couple of exercises so if anyone is willing to expand they can use the blueprint used in this PR. For example:
```
#| label: exercise-name-chunk1
#| eval: FALSE
#| code-fold: true
#| code-summary: "Show solution"
```
Ideally, break down solution chunks into steps same way as the exercises are fragmented.

Example on how to add foldable solutions to exercises

---

inst/pages/04_containers.qmd
inst/pages/11_taxonomic_information.qmd
inst/pages/12_quality_control.qmd
inst/pages/19_visualization_techniques.qmd
inst/pages/98_exercises.qmd

This is a new PR to fix issues from two other overlapping pull requests 
#372 and #371 .
I also corrected some typos.

Fix issue overlapping pull requests #371 and 372

---

inst/pages/20_beta_diversity.qmd

Just added some improvements and explanations in the RDA section.

improved documentation for rda

---

DESCRIPTION
inst/pages/14_alpha_diversity.qmd

I added the p-value correction to geom_signif in the boxplot example of chapter 6 as specified in #340.
I also added the missing packages in description as stated in #406.

added p-value correction for geom_signif
